sonar.projectKey=Scopp1337_python-project-83
sonar.organization=Scopp1337
sonar.host.url=https://sonarcloud.io
sonar.sources=page_analyzer
sonar.tests=tests
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml